version: 1.1.0
services:
  - mysql
  - php:
      version: 7.1
events:
  build:
    steps:
        - setup-project:
            type: script
            script:
              - composer install
              - cd web/themes/custom/dct_theme && npm install
