<?php

/**
 * @file
 * Contains hook implementations.
 */

use Drupal\Core\Render\BubbleableMetadata;
use Drupal\file\Entity\File;

/**
 * Implements hook_theme().
 */
function dct_homepage_theme() {
  return [
    'hosted_by_acquia_block' => [
      'variables' => [
        'link' => 'https://www.acquia.com',
      ]
    ],
    'dct_homepage_block' => [
      'variables' => [
        'date' => NULL,
        'location' => NULL,
      ],
    ],
    'dct_spread_the_word_block' => [
      'variables' => [
        'description' => NULL,
        'link' => NULL,
        'share' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_token_info().
 */
function dct_homepage_token_info() {
  $site['homepage_share_image_url'] = [
    'name' => t('Share Image URL'),
    'description' => t('The unique url of an image for sharing')
  ];

  return [
    'tokens' => ['site' => $site],
  ];

}

/**
 * Implements hook_tokens().
 */
function dct_homepage_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $token_service = \Drupal::token();

  $replacements = [];

  if ($type == 'site') {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'homepage_share_image_url':
          $url = '';
          $image = \Drupal::state()->get('dct_homepage.share_image');
          if ($image) {
            $file = File::load($image[0]);
            $url = file_create_url($file->getFileUri());
          }

          $replacements[$original] = $url;
          break;
      }
    }
  }
  return $replacements;

}
