<?php

/**
 * @file
 * Contains hook implementations.
 */

/**
 * Implements hook_theme().
 */
function dct_homepage_theme() {
  return [
    'hosted_by_acquia_block' => [
      'variables' => [
        'link' => 'https://www.acquia.com',
      ]
    ],
    'dct_homepage_block' => [
      'variables' => [
        'date' => NULL,
        'location' => NULL,
      ],
    ],
    'dct_spread_the_word_block' => [
      'variables' => [
        'description' => NULL,
        'link' => NULL,
      ],
    ],
  ];
}
