<?php

/**
 * @file
 * 
 * Commerce related functionalities.
 */


/**
 * Implements hook_form_alter().
 */
function dctransylvania_commerce_form_alter(&$form, &$form_state, $form_id) {

  if ((strpos($form_id, 'commerce_customizable_add2cart_add_to_cart_form') === 0)) {    
    $form['attributes']['product_select']['#title'] = t('Ticket type');
    $form['attributes']['product_select']['#weight'] = -15;    

    // Put the line item fields before the price field.
    $form['line_item_fields']['#weight'] = 10;

    $product = $form_state['default_product'];
    $view_mode = $form_state['context']['view_mode'];
    $form['price'] = field_view_field('commerce_product', $product, 'commerce_price', $view_mode);
    $form['price']['#weight'] = 11;
  }
  // Disable quantity field and remove update cart button on cart page.
  if ($form_id === 'views_form_commerce_cart_form_default') {    
    $form['actions']['submit']['#access'] = FALSE;
    foreach($form['edit_quantity'] as &$quantity) {
      if (is_array($quantity)) {
        $quantity['#disabled'] = TRUE;
      }
    }
  }
}
