<?php

/**
 * @file
 * Contains hook implementations.
 */

/**
 * Implements hook_theme().
 */
function dct_configurations_theme() {
  return [
    'footerblock' => [
      'variables' => [
        'link' => 'https://www.acquia.com',
      ]
    ],
    'dct_homepage_block' => [
      'variables' => [
        'date' => NULL,
        'location' => NULL,
        'description' => NULL,
      ],
    ],
  ];
}
