# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.


db:
  type: 'mariadb:10.2'
  disk: 2048
  configuration:
    schemas:
      - maindb
      - campdb
    endpoints:
      main:
        default_schema: maindb
        privileges:
          maindb: admin
      camp:
        default_schema: campdb
        privileges:
          campdb: admin
