# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.


db:
  type: 'mariadb:10.2'
  disk: 2048
  configuration:
    schemas:
      - maindb
      - 2018db
    endpoints:
      main:
        default_schema: maindb
        privileges:
          firstdb: admin
      2018:
        default_schema: 2018db
        privileges:
          seconddb: admin
