<?php

/**
 * @file
 * Contains hook implementations.
 */

/**
 * Implements hook_theme().
 */
function dct_newsletter_theme() {
  return [
    'dct_newsletter_block' => [
      'variables' => [
        'description' => NULL,
        'form' => NULL,
      ],
    ],
    'dct_newsletter_subscription_confirmation' => [],
  ];
}

/**
 * Implements hook_mail().
 */
function dct_newsletter_mail($key, &$message, $params) {
  switch ($key) {
    case 'newsletter_subscription_confirmation':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['headers']['Content-Type'] = 'text/html';
      $message['subject'] = t('Newsletter subscription');
      $body = [
        '#theme' => 'dct_newsletter_subscription_confirmation',
      ];
      $message['body'][0] = render($body);
      break;

    default:
  }
}
