<?php

/**
 * @file
 * Contains hook implementations.
 */

/**
 * Implements hook_theme().
 */
function dct_newsletter_theme() {
  return [
    'dct_newsletter_block' => [
      'variables' => [
        'description' => NULL,
        'form' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_mail().
 */
function dct_newsletter_mail($key, &$message, $params) {
  switch ($key) {
    case 'newsletter_subscription_confirmation':
      $message['from'] = ' info@drupaltransylvania.camp';
      $message['subject'] = t('Newsletter subscription');
      $message['body'][] = t('You have successfully subscribed to our newsletter!');
      break;
  }
}
